<a href="https://colab.research.google.com/github/EdwinGarcia9/Housing-Prices/blob/main/NoCountry_HouseData(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
#Librerias utilizadas
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import statistics as st
import seaborn as sns

# Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

##**1. Función de análisis.**

---

In [36]:
global df
def leer_describir(url):
  #Lectura de Datos Lima
  df= pd.read_csv(url)
  print(df.shape)
  print(df.dtypes)
  print('\n')
  #df_0= pd.DataFrame(df)
  print(df.head(5))
  return df

##**2. New York.**

---

In [37]:
df_ny=leer_describir('/content/drive/MyDrive/Colab Notebooks/Data House/NY-House-Dataset.csv')

(4801, 17)
BROKERTITLE                     object
TYPE                            object
PRICE                            int64
BEDS                             int64
BATH                           float64
PROPERTYSQFT                   float64
ADDRESS                         object
STATE                           object
MAIN_ADDRESS                    object
ADMINISTRATIVE_AREA_LEVEL_2     object
LOCALITY                        object
SUBLOCALITY                     object
STREET_NAME                     object
LONG_NAME                       object
FORMATTED_ADDRESS               object
LATITUDE                       float64
LONGITUDE                      float64
dtype: object


                                         BROKERTITLE                TYPE  \
0        Brokered by Douglas Elliman  -111 Fifth Ave      Condo for sale
1                                Brokered by Serhant      Condo for sale
2                             Brokered by Sowae Corp      House for sale
3                                Brokered by COMPASS      Condo for sale
4  Brokered by Sotheby's International Realty - E...  Townhouse for sale

       PRICE  BEDS       BATH  PROPERTYSQFT  \
0     315000     2   2.000000        1400.0
1  195000000     7  10.000000       17545.0
2     260000     4   2.000000        2015.0
3      69000     3   1.000000         445.0
4   55000000     7   2.373861       14175.0

                                             ADDRESS                    STATE  \
0                               2 E 55th St Unit 803       New York, NY 10022
1  Central Park Tower Penthouse-217 W 57th New Yo...       New York, NY 10019
2                                   620 Sinclair Ave  Staten Island, NY 10312
3                            2 E 55th St Unit 908W33      Manhattan, NY 10022
4                                        5 E 64th St       New York, NY 10065

                                        MAIN_ADDRESS  \
0             2 E 55th St Unit 803New York, NY 10022
1  Central Park Tower Penthouse-217 W 57th New Yo...
2            620 Sinclair AveStaten Island, NY 10312
3         2 E 55th St Unit 908W33Manhattan, NY 10022
4                      5 E 64th StNew York, NY 10065

  ADMINISTRATIVE_AREA_LEVEL_2  LOCALITY      SUBLOCALITY       STREET_NAME  \
0             New York County  New York        Manhattan  East 55th Street
1               United States  New York  New York County          New York
2               United States  New York  Richmond County     Staten Island
3               United States  New York  New York County          New York
4               United States  New York  New York County          New York

          LONG_NAME                                  FORMATTED_ADDRESS  \
0   Regis Residence  Regis Residence, 2 E 55th St #803, New York, N...
1  West 57th Street             217 W 57th St, New York, NY 10019, USA
2   Sinclair Avenue     620 Sinclair Ave, Staten Island, NY 10312, USA
3  East 55th Street               2 E 55th St, New York, NY 10022, USA
4  East 64th Street               5 E 64th St, New York, NY 10065, USA

    LATITUDE  LONGITUDE
0  40.761255 -73.974483
1  40.766393 -73.980991
2  40.541805 -74.196109
3  40.761398 -73.974613
4  40.767224 -73.969856

In [38]:
#Copia fuente New York
copy_df_ny= df_ny.copy()
copy_df_ny

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE
0,Brokered by Douglas Elliman -111 Fifth Ave,Condo for sale,315000,2,2.000000,1400.000000,2 E 55th St Unit 803,"New York, NY 10022","2 E 55th St Unit 803New York, NY 10022",New York County,New York,Manhattan,East 55th Street,Regis Residence,"Regis Residence, 2 E 55th St #803, New York, N...",40.761255,-73.974483
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.000000,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,New York,New York County,New York,West 57th Street,"217 W 57th St, New York, NY 10019, USA",40.766393,-73.980991
2,Brokered by Sowae Corp,House for sale,260000,4,2.000000,2015.000000,620 Sinclair Ave,"Staten Island, NY 10312","620 Sinclair AveStaten Island, NY 10312",United States,New York,Richmond County,Staten Island,Sinclair Avenue,"620 Sinclair Ave, Staten Island, NY 10312, USA",40.541805,-74.196109
3,Brokered by COMPASS,Condo for sale,69000,3,1.000000,445.000000,2 E 55th St Unit 908W33,"Manhattan, NY 10022","2 E 55th St Unit 908W33Manhattan, NY 10022",United States,New York,New York County,New York,East 55th Street,"2 E 55th St, New York, NY 10022, USA",40.761398,-73.974613
4,Brokered by Sotheby's International Realty - E...,Townhouse for sale,55000000,7,2.373861,14175.000000,5 E 64th St,"New York, NY 10065","5 E 64th StNew York, NY 10065",United States,New York,New York County,New York,East 64th Street,"5 E 64th St, New York, NY 10065, USA",40.767224,-73.969856
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,Brokered by COMPASS,Co-op for sale,599000,1,1.000000,2184.207862,222 E 80th St Apt 3A,"Manhattan, NY 10075","222 E 80th St Apt 3AManhattan, NY 10075",New York,New York County,New York,Manhattan,222,"222 E 80th St #3a, New York, NY 10075, USA",40.774350,-73.955879
4797,Brokered by Mjr Real Estate Llc,Co-op for sale,245000,1,1.000000,2184.207862,97-40 62 Dr Unit Lg,"Rego Park, NY 11374","97-40 62 Dr Unit LgRego Park, NY 11374",United States,New York,Queens County,Queens,62nd Drive,"97-40 62nd Dr, Rego Park, NY 11374, USA",40.732538,-73.860152
4798,Brokered by Douglas Elliman - 575 Madison Ave,Co-op for sale,1275000,1,1.000000,2184.207862,427 W 21st St Unit Garden,"New York, NY 10011","427 W 21st St Unit GardenNew York, NY 10011",United States,New York,New York County,New York,West 21st Street,"427 W 21st St, New York, NY 10011, USA",40.745882,-74.003398
4799,Brokered by E Realty International Corp,Condo for sale,598125,2,1.000000,655.000000,91-23 Corona Ave Unit 4G,"Elmhurst, NY 11373","91-23 Corona Ave Unit 4GElmhurst, NY 11373",New York,Queens County,Queens,Flushing,91-23,"91-23 Corona Ave. #4b, Flushing, NY 11373, USA",40.742770,-73.872752
4800,Brokered by Nyc Realty Brokers Llc,Co-op for sale,349000,1,1.000000,750.000000,460 Neptune Ave Apt 14O,"Brooklyn, NY 11224","460 Neptune Ave Apt 14OBrooklyn, NY 11224",New York,Kings County,Brooklyn,Coney Island,460,"460 Neptune Ave #14a, Brooklyn, NY 11224, USA",40.579147,-73.970949

##**3- Chicago.**

---

In [39]:
df_chicago=leer_describir('/content/drive/MyDrive/Colab Notebooks/Data House/real_estate_data_chicago.csv')

(2000, 15)
type              object
text              object
year_built       float64
beds             float64
baths            float64
baths_full       float64
baths_half       float64
garage           float64
lot_sqft         float64
sqft             float64
stories          float64
lastSoldPrice    float64
soldOn            object
listPrice        float64
status            object
dtype: object


            type                                               text  \
0  single_family  Come check out this amazing, move-in ready, 5 ...
1  single_family  Move in ready 2 story Mount Greenwood home on ...
2  single_family  Investor Special MONEY MAKING Gem. This is you...
3  single_family  Renovated Brick 1.5 story house with finished ...
4  single_family  This almost 3000sq foot home was thoughtfully ...

   year_built  beds  baths  baths_full  baths_half  garage  lot_sqft    sqft  \
0      1951.0   4.0    4.0         3.0         1.0     1.0    5615.0  3000.0
1      1922.0   4.0    3.0         2.0         1.0     2.0    6566.0  2900.0
2      1947.0   4.0    2.0         2.0         NaN     3.0    5375.0  1170.0
3      1945.0   4.0    3.0         2.0         1.0     2.0    6138.0  2511.0
4      1907.0   4.0    4.0         2.0         2.0     2.0    8476.0  2870.0

   stories  lastSoldPrice      soldOn  listPrice    status
0      2.0            NaN         NaN   750000.0  for_sale
1      2.0       105000.0  1991-04-16   499900.0  for_sale
2      2.0        60000.0  2019-10-28   325600.0  for_sale
3      2.0       170000.0  1996-05-30   620000.0  for_sale
4      3.0            NaN         NaN   850000.0  for_sale

In [40]:
#Copia de fuente Chicago
copy_df_chicago= df_chicago.copy()
copy_df_chicago

,type,text,year_built,beds,baths,baths_full,baths_half,garage,lot_sqft,sqft,stories,lastSoldPrice,soldOn,listPrice,status
0,single_family,"Come check out this amazing, move-in ready, 5 ...",1951.0,4.0,4.0,3.0,1.0,1.0,5615.0,3000.0,2.0,NaN,NaN,750000.0,for_sale
1,single_family,Move in ready 2 story Mount Greenwood home on ...,1922.0,4.0,3.0,2.0,1.0,2.0,6566.0,2900.0,2.0,105000.0,1991-04-16,499900.0,for_sale
2,single_family,Investor Special MONEY MAKING Gem. This is you...,1947.0,4.0,2.0,2.0,NaN,3.0,5375.0,1170.0,2.0,60000.0,2019-10-28,325600.0,for_sale
3,single_family,Renovated Brick 1.5 story house with finished ...,1945.0,4.0,3.0,2.0,1.0,2.0,6138.0,2511.0,2.0,170000.0,1996-05-30,620000.0,for_sale
4,single_family,This almost 3000sq foot home was thoughtfully ...,1907.0,4.0,4.0,2.0,2.0,2.0,8476.0,2870.0,3.0,NaN,NaN,850000.0,for_sale
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,single_family,WEST ELSDON BRICK SINGLE FAMILY RAISED RANCH H...,1961.0,3.0,2.0,2.0,NaN,2.0,NaN,2080.0,1.0,148000.0,2000-09-15,319900.0,for_sale
1996,condos,Welcome to your spacious three bedroom condo i...,1962.0,3.0,2.0,2.0,NaN,1.0,NaN,1498.0,27.0,NaN,NaN,260000.0,for_sale
1997,condos,Luxury Residence with jaw dropping City and Ri...,2002.0,3.0,3.0,2.0,1.0,3.0,NaN,3700.0,37.0,1705000.0,2016-06-03,1449000.0,for_sale
1998,multi_family,"Welcome to this charming & RARE, meticulously ...",1946.0,6.0,5.0,5.0,NaN,2.0,6200.0,3654.0,NaN,NaN,NaN,749000.0,for_sale
1999,single_family,"Lovely 3 bedroom, 1.5 bath brick bungalow with...",1918.0,3.0,2.0,1.0,1.0,2.0,4059.0,NaN,2.0,42500.0,1980-05-13,215000.0,for_sale

##**3.1- Transformación BD Chicago.**

---

In [41]:
#Selección de Variables | Columnas
df_chi_final= pd.DataFrame(copy_df_chicago[['lastSoldPrice','beds','baths','lot_sqft']])
df_chi_final

      lastSoldPrice  beds  baths  lot_sqft
0               NaN   4.0    4.0    5615.0
1          105000.0   4.0    3.0    6566.0
2           60000.0   4.0    2.0    5375.0
3          170000.0   4.0    3.0    6138.0
4               NaN   4.0    4.0    8476.0
...             ...   ...    ...       ...
1995       148000.0   3.0    2.0       NaN
1996            NaN   3.0    2.0       NaN
1997      1705000.0   3.0    3.0       NaN
1998            NaN   6.0    5.0    6200.0
1999        42500.0   3.0    2.0    4059.0

[2000 rows x 4 columns]

Agregado de columna STATE a Dataset Chicago para luego unir con USA.

In [53]:
#Agregando columna STATE
df_chi_final = df_chi_final.assign(state='Chicago, CHI')
#Renombrado de columnas
df_chi_final= df_chi_final.rename(columns={'lastSoldPrice':'price', 'beds': 'bed','baths':'bath', 'lot_sqft':'size(feet)'})
df_chi_final

          price  bed  bath  size(feet)         state
0           NaN  4.0   4.0      5615.0  Chicago, CHI
1      105000.0  4.0   3.0      6566.0  Chicago, CHI
2       60000.0  4.0   2.0      5375.0  Chicago, CHI
3      170000.0  4.0   3.0      6138.0  Chicago, CHI
4           NaN  4.0   4.0      8476.0  Chicago, CHI
...         ...  ...   ...         ...           ...
1995   148000.0  3.0   2.0         NaN  Chicago, CHI
1996        NaN  3.0   2.0         NaN  Chicago, CHI
1997  1705000.0  3.0   3.0         NaN  Chicago, CHI
1998        NaN  6.0   5.0      6200.0  Chicago, CHI
1999    42500.0  3.0   2.0      4059.0  Chicago, CHI

[2000 rows x 5 columns]

##**4- Estados Unidos en General.**

---

In [54]:
#Lectura de datos USA.
df_usa=leer_describir('/content/drive/MyDrive/Colab Notebooks/Data House/real_state-usa-data.csv')

(2226382, 12)
brokered_by       float64
status             object
price             float64
bed               float64
bath              float64
acre_lot          float64
street            float64
city               object
state              object
zip_code          float64
house_size        float64
prev_sold_date     object
dtype: object


   brokered_by    status     price  bed  bath  acre_lot     street  \
0     103378.0  for_sale  105000.0  3.0   2.0      0.12  1962661.0
1      52707.0  for_sale   80000.0  4.0   2.0      0.08  1902874.0
2     103379.0  for_sale   67000.0  2.0   1.0      0.15  1404990.0
3      31239.0  for_sale  145000.0  4.0   2.0      0.10  1947675.0
4      34632.0  for_sale   65000.0  6.0   2.0      0.05   331151.0

         city        state  zip_code  house_size prev_sold_date
0    Adjuntas  Puerto Rico     601.0       920.0            NaN
1    Adjuntas  Puerto Rico     601.0      1527.0            NaN
2  Juana Diaz  Puerto Rico     795.0       748.0            NaN
3       Ponce  Puerto Rico     731.0      1800.0            NaN
4    Mayaguez  Puerto Rico     680.0         NaN            NaN

In [55]:
#Copia de datos USA
copy_df_usa= df_usa.copy()
copy_df_usa

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
0,103378.0,for_sale,105000.0,3.0,2.0,0.12,1962661.0,Adjuntas,Puerto Rico,601.0,920.0,NaN
1,52707.0,for_sale,80000.0,4.0,2.0,0.08,1902874.0,Adjuntas,Puerto Rico,601.0,1527.0,NaN
2,103379.0,for_sale,67000.0,2.0,1.0,0.15,1404990.0,Juana Diaz,Puerto Rico,795.0,748.0,NaN
3,31239.0,for_sale,145000.0,4.0,2.0,0.10,1947675.0,Ponce,Puerto Rico,731.0,1800.0,NaN
4,34632.0,for_sale,65000.0,6.0,2.0,0.05,331151.0,Mayaguez,Puerto Rico,680.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2226377,23009.0,sold,359900.0,4.0,2.0,0.33,353094.0,Richland,Washington,99354.0,3600.0,2022-03-25
2226378,18208.0,sold,350000.0,3.0,2.0,0.10,1062149.0,Richland,Washington,99354.0,1616.0,2022-03-25
2226379,76856.0,sold,440000.0,6.0,3.0,0.50,405677.0,Richland,Washington,99354.0,3200.0,2022-03-24
2226380,53618.0,sold,179900.0,2.0,1.0,0.09,761379.0,Richland,Washington,99354.0,933.0,2022-03-24
2226381,108243.0,sold,580000.0,5.0,3.0,0.31,307704.0,Richland,Washington,99354.0,3615.0,2022-03-23

In [56]:
#Valores únicos en STATE. Comprobación del faltante de Chicago.
valores_unicos_state=copy_df_usa['state'].unique()
print(valores_unicos_state)
print('\n')
valores_unicos_state= pd.DataFrame(valores_unicos_state)
print(valores_unicos_state.value_counts())
print('\n')
print(f'Total de valores unicos en variable STATE:',valores_unicos_state.value_counts().sum())

['Puerto Rico' 'Virgin Islands' 'Massachusetts' 'Connecticut'
 'New Hampshire' 'Vermont' 'New Jersey' 'New York' 'South Carolina'
 'Tennessee' 'Rhode Island' 'Virginia' 'Wyoming' 'Maine' 'Georgia'
 'Pennsylvania' 'West Virginia' 'Delaware' 'Louisiana' 'Ohio' 'California'
 'Colorado' 'Maryland' 'Missouri' 'District of Columbia' 'Wisconsin'
 'North Carolina' 'Kentucky' 'Michigan' 'Mississippi' 'Florida' 'Alabama'
 'New Brunswick' nan 'Texas' 'Arkansas' 'Idaho' 'Indiana' 'Illinois'
 'New Mexico' 'Iowa' 'Minnesota' 'South Dakota' 'Nebraska' 'North Dakota'
 'Montana' 'Oklahoma' 'Kansas' 'Oregon' 'Utah' 'Nevada' 'Washington'
 'Arizona' 'Hawaii' 'Guam' 'Alaska']


Alabama                 1
Puerto Rico             1
New Brunswick           1
New Hampshire           1
New Jersey              1
New Mexico              1
New York                1
North Carolina          1
North Dakota            1
Ohio                    1
Oklahoma                1
Oregon                  1
Pennsylvania            1
Rhode Island            1
Nebraska                1
South Carolina          1
South Dakota            1
Tennessee               1
Texas                   1
Utah                    1
Vermont                 1
Virgin Islands          1
Virginia                1
Washington              1
West Virginia           1
Wisconsin               1
Nevada                  1
Montana                 1
Alaska                  1
Idaho                   1
Arizona                 1
Arkansas                1
California              1
Colorado                1
Connecticut             1
Delaware                1
District of Columbia    1
Florida                 1
Georgia                 1
Guam                    1
Hawaii                  1
Illinois                1
Missouri                1
Indiana                 1
Iowa                    1
Kansas                  1
Kentucky                1
Louisiana               1
Maine                   1
Maryland                1
Massachusetts           1
Michigan                1
Minnesota               1
Mississippi             1
Wyoming                 1
Name: count, dtype: int64


Total de valores unicos en variable STATE: 55

##**4.1- Tranformación Datos Estados Unidos**

---

In [57]:
#Selección de Variables | Columnas
df_usa_final = copy_df_usa[copy_df_usa['status'] == 'for_sale'][['price', 'bed', 'bath','house_size','state']]
df_usa_final

             price  bed  bath  house_size        state
0         105000.0  3.0   2.0       920.0  Puerto Rico
1          80000.0  4.0   2.0      1527.0  Puerto Rico
2          67000.0  2.0   1.0       748.0  Puerto Rico
3         145000.0  4.0   2.0      1800.0  Puerto Rico
4          65000.0  6.0   2.0         NaN  Puerto Rico
...            ...  ...   ...         ...          ...
1414368   299000.0  NaN   NaN         NaN       Alaska
1414369   299000.0  NaN   NaN         NaN       Alaska
1414370   199000.0  NaN   NaN         NaN       Alaska
1414371  1575000.0  NaN   NaN         NaN       Alaska
1414372  1575000.0  NaN   NaN         NaN       Alaska

[1389306 rows x 5 columns]

In [58]:
#Comprobación de datos "for_sale"
cantidad_for_sale = copy_df_usa['status'].value_counts().get('for_sale', 0)
print("Cantidad de 'for sale':", cantidad_for_sale)

Cantidad de 'for sale': 1389306

In [59]:
#Demora de uso de funcion Lamda es de aproximadamente 3 minutos.
#df_usa_final = copy_df_usa.apply(lambda row: pd.DataFrame(copy_df_usa[['price', 'bed', 'bath','state','house_size']]) if row['status'] == 'for_sale' else row, axis=1)

In [60]:
#Renombrado de variables USA.
df_usa_final= df_usa_final.rename(columns={'house_size':'size(feet)'})
df_final=pd.concat([df_usa_final, df_chi_final])
df_final=df_final.reset_index(drop=True)
df_final

             price  bed  bath  size(feet)         state
0         105000.0  3.0   2.0       920.0   Puerto Rico
1          80000.0  4.0   2.0      1527.0   Puerto Rico
2          67000.0  2.0   1.0       748.0   Puerto Rico
3         145000.0  4.0   2.0      1800.0   Puerto Rico
4          65000.0  6.0   2.0         NaN   Puerto Rico
...            ...  ...   ...         ...           ...
1391301   148000.0  3.0   2.0         NaN  Chicago, CHI
1391302        NaN  3.0   2.0         NaN  Chicago, CHI
1391303  1705000.0  3.0   3.0         NaN  Chicago, CHI
1391304        NaN  6.0   5.0      6200.0  Chicago, CHI
1391305    42500.0  3.0   2.0      4059.0  Chicago, CHI

[1391306 rows x 5 columns]

In [61]:
df_final.to_csv('/content/drive/MyDrive/Colab Notebooks/Data House/Data_Final_realE_USA(2).csv', index=True)